# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, macOS-latest, windows-latest ]
        # Use both LTS releases and latest one for tests
        jdk: [ 11, 17, 18 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: -Pclean-release build
      - name: Test with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: test
      - name: TestCoverage with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: jacocoTestReport
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ./build/reports/jacoco/test/jacocoTestReport.xml